packages:
  - apps/*
  - '!apps/web-old' # Excluded - legacy app, duplicates dependencies (~460MB savings)
  - packages/*
  - packages/shared/*
  - services/*
  # Note: scripts/* excluded - standalone utilities with own dependencies

ignoredBuiltDependencies:
  - sharp
